services:
  web:
  image: web:V1.0
    build: 
      context: .
      dockerfile: ./Dockerfile.prod
    command: gunicorn weducar.wsgi:application --bind 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - ./.env