# Generated by Django 5.1.2 on 2024-11-05 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(db_column='usuario', max_length=45, unique=True, verbose_name='Nome de Usuário')),
                ('access_count', models.IntegerField(db_column='acessos', default=0, verbose_name='Número de Acessos')),
                ('last_access', models.DateTimeField(blank=True, db_column='ultimo_acesso', null=True, verbose_name='Último Acesso')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Membro da Equipe')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Superusuário')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'db_table': 'usuarios',
            },
        ),
    ]
