# Generated by Django 5.1.2 on 2024-10-17 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_type', models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('gestor', 'Gestor'), ('docente', 'Docente')], db_column='tipo', max_length=11)),
                ('username', models.CharField(db_column='usuario', max_length=45, unique=True)),
                ('access_count', models.IntegerField(db_column='acessos', default=0)),
                ('last_access', models.DateTimeField(blank=True, db_column='ultimo_acesso', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'db_table': 'usuarios',
            },
        ),
    ]
