# Generated by Django 5.1.2 on 2024-10-17 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('academic_year_id', models.AutoField(db_column='id_ano_letivo', primary_key=True, serialize=False)),
                ('description', models.IntegerField(db_column='descricao')),
            ],
            options={
                'verbose_name': 'Ano Letivo',
                'verbose_name_plural': 'Anos Letivos',
                'db_table': 'anos_letivos',
            },
        ),
        migrations.CreateModel(
            name='CurricularMatrix',
            fields=[
                ('matrix_id', models.AutoField(db_column='id_matriz', primary_key=True, serialize=False)),
                ('description', models.CharField(db_column='descricao', max_length=45)),
                ('matrix_year', models.IntegerField(db_column='ano_matriz')),
            ],
            options={
                'verbose_name': 'Matriz Curricular',
                'verbose_name_plural': 'Matrizes Curriculares',
                'db_table': 'matriz_curricular',
            },
        ),
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('diary_id', models.AutoField(db_column='id_diario', primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Diário',
                'verbose_name_plural': 'Diários',
                'db_table': 'diarios',
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('evaluation_id', models.AutoField(db_column='id_avaliacao', primary_key=True, serialize=False)),
                ('description', models.CharField(db_column='descricao', max_length=45)),
                ('recovery', models.IntegerField(db_column='recuperacao')),
                ('group', models.CharField(blank=True, db_column='grupo', max_length=45, null=True)),
            ],
            options={
                'verbose_name': 'Avaliação',
                'verbose_name_plural': 'Avaliações',
                'db_table': 'avaliacoes',
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('grade_id', models.AutoField(db_column='id_nota', primary_key=True, serialize=False)),
                ('grade', models.DecimalField(decimal_places=2, max_digits=2)),
            ],
            options={
                'verbose_name': 'Nota',
                'verbose_name_plural': 'Notas',
                'db_table': 'notas',
            },
        ),
        migrations.CreateModel(
            name='LessonContent',
            fields=[
                ('lesson_content_id', models.AutoField(db_column='id_conteudo_aula', primary_key=True, serialize=False)),
                ('description', models.TextField(db_column='descricao')),
                ('status', models.CharField(blank=True, db_column='status', max_length=1, null=True)),
                ('registration_date', models.DateField(db_column='data_registro')),
            ],
            options={
                'verbose_name': 'Conteúdo da Aula',
                'verbose_name_plural': 'Conteúdos das Aulas',
                'db_table': 'conteudo_aula',
            },
        ),
        migrations.CreateModel(
            name='SchoolYear',
            fields=[
                ('school_year_id', models.AutoField(db_column='id_ano_escolar', primary_key=True, serialize=False)),
                ('series', models.CharField(db_column='serie', max_length=45)),
                ('stage', models.CharField(db_column='etapa', max_length=2)),
            ],
            options={
                'verbose_name': 'Ano Escolar',
                'verbose_name_plural': 'Anos Escolares',
                'db_table': 'anos_escolares',
            },
        ),
        migrations.CreateModel(
            name='CurricularComponent',
            fields=[
                ('component_id', models.AutoField(db_column='id_componente', primary_key=True, serialize=False)),
                ('description', models.CharField(db_column='descricao', max_length=45)),
                ('instance_id', models.ForeignKey(db_column='id_instancia', on_delete=django.db.models.deletion.DO_NOTHING, to='locations.instance')),
            ],
            options={
                'verbose_name': 'Componente Curricular',
                'verbose_name_plural': 'Componentes Curriculares',
                'db_table': 'componentes_curriculares',
            },
        ),
        migrations.CreateModel(
            name='CurricularComponentMatrix',
            fields=[
                ('matrix_component_id', models.AutoField(db_column='id_matriz_componente', primary_key=True, serialize=False)),
                ('stage', models.CharField(max_length=2)),
                ('workload', models.IntegerField()),
                ('component_id', models.ForeignKey(db_column='id_componente', on_delete=django.db.models.deletion.DO_NOTHING, to='academics.curricularcomponent')),
                ('matrix_id', models.ForeignKey(db_column='id_matriz', on_delete=django.db.models.deletion.DO_NOTHING, to='academics.curricularmatrix')),
            ],
            options={
                'verbose_name': 'Componente da Matriz Curricular',
                'verbose_name_plural': 'Componentes da Matriz Curricular',
                'db_table': 'matriz_componentes',
            },
        ),
    ]
