# Generated by Django 5.1.2 on 2024-11-05 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('administration', '0001_initial'),
        ('locations', '0001_initial'),
        ('management', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='class_id',
            field=models.ForeignKey(db_column='id_turma', on_delete=django.db.models.deletion.DO_NOTHING, to='management.classe'),
        ),
        migrations.AddField(
            model_name='diary',
            name='employee_id',
            field=models.ForeignKey(db_column='id_funcionario', on_delete=django.db.models.deletion.DO_NOTHING, to='administration.employee'),
        ),
        migrations.AddField(
            model_name='diary',
            name='matrix_component_id',
            field=models.ForeignKey(db_column='id_matriz_componente', on_delete=django.db.models.deletion.DO_NOTHING, to='academics.curricularcomponentmatrix'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='academic_year_id',
            field=models.ForeignKey(db_column='id_ano_letivo', on_delete=django.db.models.deletion.DO_NOTHING, to='academics.academicyear'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='instance_id',
            field=models.ForeignKey(db_column='id_instancia', on_delete=django.db.models.deletion.DO_NOTHING, to='locations.instance'),
        ),
        migrations.AddField(
            model_name='grade',
            name='diary_id',
            field=models.ForeignKey(db_column='id_diario', on_delete=django.db.models.deletion.DO_NOTHING, to='academics.diary'),
        ),
        migrations.AddField(
            model_name='grade',
            name='evaluation_id',
            field=models.ForeignKey(db_column='id_avaliacao', on_delete=django.db.models.deletion.DO_NOTHING, to='academics.evaluation'),
        ),
        migrations.AddField(
            model_name='grade',
            name='student_registration',
            field=models.ForeignKey(db_column='aluno_matricula', on_delete=django.db.models.deletion.DO_NOTHING, to='students.student'),
        ),
        migrations.AddField(
            model_name='lessoncontent',
            name='diary_id',
            field=models.ForeignKey(db_column='id_diario', on_delete=django.db.models.deletion.DO_NOTHING, to='academics.diary'),
        ),
        migrations.AddField(
            model_name='lessoncontent',
            name='schedule_id',
            field=models.ForeignKey(db_column='id_grade_horario', on_delete=django.db.models.deletion.DO_NOTHING, to='administration.schedulegrid'),
        ),
        migrations.AddField(
            model_name='schoolyear',
            name='academic_year',
            field=models.ForeignKey(db_column='id_ano_letivo', on_delete=django.db.models.deletion.DO_NOTHING, to='academics.academicyear', verbose_name='Ano Letivo'),
        ),
        migrations.AddField(
            model_name='schoolyear',
            name='curriculum_matrix',
            field=models.ForeignKey(db_column='id_matriz', on_delete=django.db.models.deletion.DO_NOTHING, to='academics.curricularmatrix', verbose_name='Matriz Curricular'),
        ),
        migrations.AddField(
            model_name='schoolyear',
            name='school',
            field=models.ForeignKey(db_column='id_escola', on_delete=django.db.models.deletion.DO_NOTHING, to='administration.school', verbose_name='Escola'),
        ),
    ]
