# Generated by Django 5.1.2 on 2024-10-17 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('administration', '0001_initial'),
        ('locations', '0001_initial'),
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentStatus',
            fields=[
                ('student_status_id', models.AutoField(db_column='id_situacao_aluno', primary_key=True, serialize=False)),
                ('description', models.CharField(db_column='descricao', max_length=45)),
            ],
            options={
                'verbose_name': 'Situação do Aluno',
                'verbose_name_plural': 'Situações do Aluno',
                'db_table': 'situacao_aluno',
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('history_id', models.AutoField(db_column='id_historico', primary_key=True, serialize=False)),
                ('institution', models.CharField(db_column='estabelecimento', max_length=45)),
                ('year', models.CharField(db_column='ano', max_length=45)),
                ('eja', models.IntegerField(blank=True, db_column='eja', null=True)),
                ('resolution', models.CharField(blank=True, db_column='resolucao', max_length=45, null=True)),
                ('result', models.CharField(db_column='resultado', max_length=10)),
                ('workload', models.IntegerField(blank=True, db_column='carga_horaria', null=True)),
                ('observations', models.TextField(blank=True, db_column='observacoes', null=True)),
                ('city_id', models.ForeignKey(db_column='id_cidade', on_delete=django.db.models.deletion.DO_NOTHING, to='locations.city')),
                ('school_id', models.ForeignKey(db_column='id_escola', on_delete=django.db.models.deletion.DO_NOTHING, to='administration.school')),
                ('school_year_id', models.ForeignKey(db_column='id_ano_escolar', on_delete=django.db.models.deletion.DO_NOTHING, to='academics.schoolyear')),
            ],
            options={
                'verbose_name': 'Histórico',
                'verbose_name_plural': 'Históricos',
                'db_table': 'historico',
            },
        ),
        migrations.CreateModel(
            name='HistoryArea',
            fields=[
                ('school_area_id', models.AutoField(db_column='id_escolar_area', primary_key=True, serialize=False)),
                ('grade', models.DecimalField(db_column='nota', decimal_places=2, max_digits=2)),
                ('workload', models.IntegerField(blank=True, db_column='carga_horaria', null=True)),
                ('component_id', models.ForeignKey(db_column='id_componente', on_delete=django.db.models.deletion.DO_NOTHING, to='academics.curricularcomponent')),
                ('history_id', models.ForeignKey(db_column='id_historico', on_delete=django.db.models.deletion.DO_NOTHING, to='students.history')),
            ],
            options={
                'verbose_name': 'Área do Histórico',
                'verbose_name_plural': 'Áreas do Histórico',
                'db_table': 'historico_areas',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('registration', models.PositiveIntegerField(db_column='matricula', primary_key=True, serialize=False)),
                ('census_id', models.IntegerField(blank=True, db_column='id_censo', null=True)),
                ('name', models.CharField(db_column='nome', max_length=45)),
                ('gender', models.CharField(db_column='sexo', max_length=1)),
                ('birth_date', models.DateField(db_column='data_nascimento')),
                ('father_name', models.CharField(blank=True, db_column='pai_nome', max_length=255, null=True)),
                ('father_phone', models.CharField(blank=True, db_column='pai_telefone', max_length=11, null=True)),
                ('father_rg', models.CharField(blank=True, db_column='pai_rg', max_length=45, null=True)),
                ('father_cpf', models.CharField(blank=True, db_column='pai_cpf', max_length=11, null=True)),
                ('mother_name', models.CharField(blank=True, db_column='mae_nome', max_length=255, null=True)),
                ('mother_phone', models.CharField(blank=True, db_column='mae_telefone', max_length=11, null=True)),
                ('mother_rg', models.CharField(blank=True, db_column='mae_rg', max_length=45, null=True)),
                ('mother_cpf', models.CharField(blank=True, db_column='mae_cpf', max_length=11, null=True)),
                ('responsible_relationship', models.CharField(db_column='parentesco_responsavel', max_length=45)),
                ('responsible_name', models.CharField(db_column='responsavel_nome', max_length=255)),
                ('responsible_phone', models.CharField(blank=True, db_column='responsavel_telefone', max_length=11, null=True)),
                ('responsible_rg', models.CharField(blank=True, db_column='responsavel_rg', max_length=45, null=True)),
                ('responsible_cpf', models.CharField(blank=True, db_column='responsavel_cpf', max_length=11, null=True)),
                ('address', models.CharField(blank=True, db_column='endereco', max_length=45, null=True)),
                ('neighborhood', models.CharField(blank=True, db_column='bairro', max_length=45, null=True)),
                ('allergy_check', models.IntegerField(blank=True, db_column='check_alergia', null=True)),
                ('allergy_observations', models.CharField(blank=True, db_column='obs_alergia', max_length=255, null=True)),
                ('medical_monitoring_check', models.IntegerField(blank=True, db_column='check_acompanhamento_medico', null=True)),
                ('medical_monitoring_observations', models.CharField(blank=True, db_column='obs_acompanhamento_medico', max_length=255, null=True)),
                ('physical_activity_restriction_check', models.IntegerField(blank=True, db_column='check_restricao_atv_fisica', null=True)),
                ('physical_activity_restriction_observations', models.CharField(blank=True, db_column='obs_restricao_atv_fisica', max_length=255, null=True)),
                ('disorder_check', models.IntegerField(blank=True, db_column='check_disturbio', null=True)),
                ('disorder_observations', models.CharField(blank=True, db_column='obs_disturbio', max_length=255, null=True)),
                ('disorder_instructions', models.TextField(blank=True, db_column='instrucoes_disturbio', null=True)),
                ('medication_check', models.IntegerField(blank=True, db_column='check_medicacao', null=True)),
                ('medication_observations', models.CharField(blank=True, db_column='obs_medicacao', max_length=255, null=True)),
                ('food_restriction_check', models.FloatField(blank=True, db_column='check_restricao_alimentar', null=True)),
                ('food_restriction_observations', models.CharField(blank=True, db_column='obs_restricao_alimentar', max_length=255, null=True)),
                ('image_right_check', models.IntegerField(blank=True, db_column='check_direito_imagem', null=True)),
                ('sus_number', models.CharField(blank=True, db_column='num_sus', max_length=15, null=True)),
                ('nis_number', models.CharField(blank=True, db_column='num_nis', max_length=11, null=True)),
                ('old_birth_certificate_check', models.IntegerField(blank=True, db_column='check_certidao_antiga', null=True)),
                ('birth_certificate', models.CharField(blank=True, db_column='certidao_nascimento', max_length=255, null=True)),
                ('birth_certificate_issue_date', models.DateField(blank=True, db_column='data_expedicao_certidao', null=True)),
                ('birth_certificate_registry', models.CharField(blank=True, db_column='certidao_cartorio', max_length=255, null=True)),
                ('birthplace', models.TextField(blank=True, db_column='naturalidade', null=True)),
                ('rg', models.CharField(blank=True, db_column='rg', max_length=45, null=True)),
                ('cpf', models.CharField(blank=True, db_column='cpf', max_length=11, null=True)),
                ('school_transport_check', models.IntegerField(blank=True, db_column='check_trasnporte_escolar', null=True)),
                ('disability_check', models.IntegerField(blank=True, db_column='check_pcd', null=True)),
                ('disability_observations', models.CharField(blank=True, db_column='obs_pcd', max_length=255, null=True)),
                ('aee_check', models.IntegerField(blank=True, db_column='check_aee', null=True)),
                ('photo', models.TextField(blank=True, db_column='foto', null=True)),
                ('city_id', models.ForeignKey(db_column='id_cidade', on_delete=django.db.models.deletion.DO_NOTHING, to='locations.city')),
                ('housing_id', models.ForeignKey(db_column='id_moradia', on_delete=django.db.models.deletion.DO_NOTHING, to='locations.housing')),
                ('instance_id', models.ForeignKey(db_column='id_instancia', on_delete=django.db.models.deletion.DO_NOTHING, to='locations.instance')),
                ('student_status_id', models.ForeignKey(db_column='id_situacao_aluno', on_delete=django.db.models.deletion.DO_NOTHING, to='students.studentstatus')),
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
                'db_table': 'alunos',
            },
        ),
        migrations.AddField(
            model_name='history',
            name='student_registration',
            field=models.ForeignKey(db_column='aluno_matricula', on_delete=django.db.models.deletion.DO_NOTHING, to='students.student'),
        ),
        migrations.CreateModel(
            name='StudentClasses',
            fields=[
                ('class_id_student', models.AutoField(db_column='id_turma_aluno', primary_key=True, serialize=False)),
                ('class_id', models.ForeignKey(db_column='id_turma', on_delete=django.db.models.deletion.DO_NOTHING, to='management.classe')),
                ('student_enrollment', models.ForeignKey(db_column='aluno_matricula', on_delete=django.db.models.deletion.DO_NOTHING, to='students.student')),
            ],
            options={
                'verbose_name': 'Turma do Aluno',
                'verbose_name_plural': 'Turmas dos Alunos',
                'db_table': 'turmas_aluno',
            },
        ),
    ]
