# Generated by Django 5.1.2 on 2024-11-05 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('administration', '0001_initial'),
        ('locations', '0001_initial'),
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentStatus',
            fields=[
                ('id', models.AutoField(db_column='id_situacao_aluno', primary_key=True, serialize=False, verbose_name='ID da Situação Aluno')),
                ('description', models.CharField(db_column='descricao', max_length=45, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Situação do Aluno',
                'verbose_name_plural': 'Situações do Aluno',
                'db_table': 'situacao_aluno',
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('history_id', models.AutoField(db_column='id_historico', primary_key=True, serialize=False, verbose_name='ID do Histórico')),
                ('institution', models.CharField(db_column='estabelecimento', max_length=45, verbose_name='Estabelecimento')),
                ('year', models.CharField(db_column='ano', max_length=45, verbose_name='Ano')),
                ('eja', models.IntegerField(blank=True, db_column='eja', null=True, verbose_name='EJA')),
                ('resolution', models.CharField(blank=True, db_column='resolucao', max_length=45, null=True, verbose_name='Resolução')),
                ('result', models.CharField(db_column='resultado', max_length=10, verbose_name='Resultado')),
                ('workload', models.IntegerField(blank=True, db_column='carga_horaria', null=True, verbose_name='Carga Horária')),
                ('observations', models.TextField(blank=True, db_column='observacoes', null=True, verbose_name='Observações')),
                ('city_id', models.ForeignKey(db_column='id_cidade', on_delete=django.db.models.deletion.DO_NOTHING, to='locations.city', verbose_name='Cidade')),
                ('school_id', models.ForeignKey(db_column='id_escola', on_delete=django.db.models.deletion.DO_NOTHING, to='administration.school', verbose_name='Escola')),
                ('school_year_id', models.ForeignKey(db_column='id_ano_escolar', on_delete=django.db.models.deletion.DO_NOTHING, to='academics.schoolyear', verbose_name='Ano Escolar')),
            ],
            options={
                'verbose_name': 'Histórico',
                'verbose_name_plural': 'Históricos',
                'db_table': 'historico',
            },
        ),
        migrations.CreateModel(
            name='HistoryArea',
            fields=[
                ('school_area_id', models.AutoField(db_column='id_escolar_area', primary_key=True, serialize=False, verbose_name='ID da Área Escolar')),
                ('grade', models.DecimalField(db_column='nota', decimal_places=2, max_digits=2, verbose_name='Nota')),
                ('workload', models.IntegerField(blank=True, db_column='carga_horaria', null=True, verbose_name='Carga Horária')),
                ('component_id', models.ForeignKey(db_column='id_componente', on_delete=django.db.models.deletion.DO_NOTHING, to='academics.curricularcomponent', verbose_name='Componente Curricular')),
                ('history_id', models.ForeignKey(db_column='id_historico', on_delete=django.db.models.deletion.DO_NOTHING, to='students.history', verbose_name='Histórico')),
            ],
            options={
                'verbose_name': 'Área do Histórico',
                'verbose_name_plural': 'Áreas do Histórico',
                'db_table': 'historico_areas',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('registration', models.PositiveIntegerField(db_column='matricula', primary_key=True, serialize=False, verbose_name='Matrícula')),
                ('census_id', models.IntegerField(blank=True, db_column='id_censo', null=True, verbose_name='ID do Censo')),
                ('name', models.CharField(db_column='nome', max_length=45, verbose_name='Nome')),
                ('gender', models.CharField(db_column='sexo', max_length=1, verbose_name='Sexo')),
                ('birth_date', models.DateField(db_column='data_nascimento', verbose_name='Data de Nascimento')),
                ('father_name', models.CharField(blank=True, db_column='pai_nome', max_length=255, null=True, verbose_name='Nome do Pai')),
                ('father_phone', models.CharField(blank=True, db_column='pai_telefone', max_length=11, null=True, verbose_name='Telefone do Pai')),
                ('father_rg', models.CharField(blank=True, db_column='pai_rg', max_length=45, null=True, verbose_name='RG do Pai')),
                ('father_cpf', models.CharField(blank=True, db_column='pai_cpf', max_length=11, null=True, verbose_name='CPF do Pai')),
                ('mother_name', models.CharField(blank=True, db_column='mae_nome', max_length=255, null=True, verbose_name='Nome da Mãe')),
                ('mother_phone', models.CharField(blank=True, db_column='mae_telefone', max_length=11, null=True, verbose_name='Telefone da Mãe')),
                ('mother_rg', models.CharField(blank=True, db_column='mae_rg', max_length=45, null=True, verbose_name='RG da Mãe')),
                ('mother_cpf', models.CharField(blank=True, db_column='mae_cpf', max_length=11, null=True, verbose_name='CPF da Mãe')),
                ('responsible_relationship', models.CharField(db_column='parentesco_responsavel', max_length=45, verbose_name='Parentesco do Responsável')),
                ('responsible_name', models.CharField(db_column='responsavel_nome', max_length=255, verbose_name='Nome do Responsável')),
                ('responsible_phone', models.CharField(blank=True, db_column='responsavel_telefone', max_length=11, null=True, verbose_name='Telefone do Responsável')),
                ('responsible_rg', models.CharField(blank=True, db_column='responsavel_rg', max_length=45, null=True, verbose_name='RG do Responsável')),
                ('responsible_cpf', models.CharField(blank=True, db_column='responsavel_cpf', max_length=11, null=True, verbose_name='CPF do Responsável')),
                ('address', models.CharField(blank=True, db_column='endereco', max_length=45, null=True, verbose_name='Endereço')),
                ('neighborhood', models.CharField(blank=True, db_column='bairro', max_length=45, null=True, verbose_name='Bairro')),
                ('allergy_check', models.IntegerField(blank=True, db_column='check_alergia', null=True, verbose_name='Check Alergia')),
                ('allergy_observations', models.CharField(blank=True, db_column='obs_alergia', max_length=255, null=True, verbose_name='Observações sobre Alergia')),
                ('medical_monitoring_check', models.IntegerField(blank=True, db_column='check_acompanhamento_medico', null=True, verbose_name='Check Acompanhamento Médico')),
                ('medical_monitoring_observations', models.CharField(blank=True, db_column='obs_acompanhamento_medico', max_length=255, null=True, verbose_name='Observações sobre Acompanhamento Médico')),
                ('physical_activity_restriction_check', models.IntegerField(blank=True, db_column='check_restricao_atv_fisica', null=True, verbose_name='Check Restrição de Atividade Física')),
                ('physical_activity_restriction_observations', models.CharField(blank=True, db_column='obs_restricao_atv_fisica', max_length=255, null=True, verbose_name='Observações sobre Restrição de Atividade Física')),
                ('disorder_check', models.IntegerField(blank=True, db_column='check_disturbio', null=True, verbose_name='Check Distúrbio')),
                ('disorder_observations', models.CharField(blank=True, db_column='obs_disturbio', max_length=255, null=True, verbose_name='Observações sobre Distúrbio')),
                ('disorder_instructions', models.TextField(blank=True, db_column='instrucoes_disturbio', null=True, verbose_name='Instruções sobre Distúrbio')),
                ('medication_check', models.IntegerField(blank=True, db_column='check_medicacao', null=True, verbose_name='Check Medicação')),
                ('medication_observations', models.CharField(blank=True, db_column='obs_medicacao', max_length=255, null=True, verbose_name='Observações sobre Medicação')),
                ('food_restriction_check', models.FloatField(blank=True, db_column='check_restricao_alimentar', null=True, verbose_name='Check Restrição Alimentar')),
                ('food_restriction_observations', models.CharField(blank=True, db_column='obs_restricao_alimentar', max_length=255, null=True, verbose_name='Observações de Restrição Alimentar')),
                ('image_right_check', models.IntegerField(blank=True, db_column='check_direito_imagem', null=True, verbose_name='Check Direito de Imagem')),
                ('sus_number', models.CharField(blank=True, db_column='num_sus', max_length=15, null=True, verbose_name='Número do SUS')),
                ('nis_number', models.CharField(blank=True, db_column='num_nis', max_length=11, null=True, verbose_name='Número do NIS')),
                ('old_birth_certificate_check', models.IntegerField(blank=True, db_column='check_certidao_antiga', null=True, verbose_name='Check Certidão Antiga')),
                ('birth_certificate', models.CharField(blank=True, db_column='certidao_nascimento', max_length=255, null=True, verbose_name='Certidão de Nascimento')),
                ('birth_certificate_issue_date', models.DateField(blank=True, db_column='data_expedicao_certidao', null=True, verbose_name='Data de Expedição da Certidão')),
                ('birth_certificate_registry', models.CharField(blank=True, db_column='certidao_cartorio', max_length=255, null=True, verbose_name='Cartório da Certidão')),
                ('birthplace', models.TextField(blank=True, db_column='naturalidade', null=True, verbose_name='Naturalidade')),
                ('rg', models.CharField(blank=True, db_column='rg', max_length=45, null=True, verbose_name='RG')),
                ('cpf', models.CharField(blank=True, db_column='cpf', max_length=11, null=True, verbose_name='CPF')),
                ('school_transport_check', models.IntegerField(blank=True, db_column='check_transporte_escolar', null=True, verbose_name='Check Transporte Escolar')),
                ('disability_check', models.IntegerField(blank=True, db_column='check_pcd', null=True, verbose_name='Check PCD')),
                ('disability_observations', models.CharField(blank=True, db_column='obs_pcd', max_length=255, null=True, verbose_name='Observações de PCD')),
                ('aee_check', models.IntegerField(blank=True, db_column='check_aee', null=True, verbose_name='Check AEE')),
                ('photo', models.TextField(blank=True, db_column='foto', null=True, verbose_name='Foto')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Data de Entrada')),
                ('date_changed', models.DateTimeField(auto_now=True, verbose_name='Data de alteração')),
                ('city', models.ForeignKey(db_column='id_cidade', on_delete=django.db.models.deletion.DO_NOTHING, to='locations.city', verbose_name='Cidade')),
                ('housing_id', models.ForeignKey(db_column='id_moradia', on_delete=django.db.models.deletion.DO_NOTHING, to='locations.housing', verbose_name='Moradia')),
                ('instance', models.ForeignKey(db_column='id_instancia', on_delete=django.db.models.deletion.DO_NOTHING, to='locations.instance', verbose_name='Instancia')),
                ('student_status', models.ForeignKey(db_column='id_situacao_aluno', on_delete=django.db.models.deletion.DO_NOTHING, to='students.studentstatus', verbose_name='Situacao Aluno')),
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
                'db_table': 'alunos',
            },
        ),
        migrations.AddField(
            model_name='history',
            name='student_registration',
            field=models.ForeignKey(db_column='aluno_matricula', on_delete=django.db.models.deletion.DO_NOTHING, to='students.student', verbose_name='Matrícula do Aluno'),
        ),
        migrations.CreateModel(
            name='StudentClasses',
            fields=[
                ('class_id_student', models.AutoField(db_column='id_turma_aluno', primary_key=True, serialize=False, verbose_name='ID da Turma do Aluno')),
                ('classe', models.ForeignKey(db_column='id_turma', on_delete=django.db.models.deletion.DO_NOTHING, to='management.classe', verbose_name='Turma')),
                ('student_enrollment', models.ForeignKey(db_column='aluno_matricula', on_delete=django.db.models.deletion.DO_NOTHING, to='students.student', verbose_name='Matrícula do Aluno')),
            ],
            options={
                'verbose_name': 'Turma do Aluno',
                'verbose_name_plural': 'Turmas dos Alunos',
                'db_table': 'turmas_aluno',
            },
        ),
    ]
