# Generated by Django 5.1.2 on 2024-11-06 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(db_column='descricao', max_length=50, unique=True, verbose_name='Descrição da Cor')),
            ],
            options={
                'verbose_name': 'Cor',
                'verbose_name_plural': 'Cores',
                'db_table': 'cor',
            },
        ),
        migrations.RenameField(
            model_name='student',
            old_name='housing_id',
            new_name='housing',
        ),
        migrations.AlterField(
            model_name='student',
            name='father_cpf',
            field=models.CharField(blank=True, db_column='pai_cpf', max_length=11, null=True, unique=True, verbose_name='CPF do Pai'),
        ),
        migrations.AlterField(
            model_name='student',
            name='registration',
            field=models.PositiveIntegerField(blank=True, db_column='matricula', primary_key=True, serialize=False, verbose_name='Matrícula'),
        ),
        migrations.AlterField(
            model_name='studentclasses',
            name='student_enrollment',
            field=models.ForeignKey(db_column='aluno_matricula', on_delete=django.db.models.deletion.DO_NOTHING, related_name='studentclasses', to='students.student', verbose_name='Matrícula do Aluno'),
        ),
    ]
