# Generated by Django 5.1.2 on 2024-11-06 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_student_aee_check_alter_student_allergy_check_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='food_restriction_check',
            field=models.IntegerField(blank=True, db_column='check_restricao_alimentar', default=0, null=True, verbose_name='Check Restrição Alimentar'),
        ),
    ]
