# Generated by Django 5.1.2 on 2024-11-05 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Housing',
            fields=[
                ('housing_id', models.AutoField(db_column='id_moradia', primary_key=True, serialize=False, verbose_name='ID da Moradia')),
                ('description', models.CharField(db_column='descricao', max_length=255, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Moradia',
                'verbose_name_plural': 'Moradias',
                'db_table': 'moradia',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(db_column='id_estado', primary_key=True, serialize=False, verbose_name='ID do Estado')),
                ('uf', models.CharField(db_column='uf', max_length=2, verbose_name='UF')),
                ('name', models.CharField(db_column='nome', max_length=45, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
                'db_table': 'estados',
            },
        ),
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.AutoField(db_column='id_instancia', primary_key=True, serialize=False, verbose_name='ID da Instância')),
                ('name', models.CharField(db_column='nome', max_length=45, verbose_name='Nome')),
                ('address', models.CharField(db_column='endereco', max_length=45, verbose_name='Endereço')),
                ('neighborhood', models.CharField(db_column='bairro', max_length=45, verbose_name='Bairro')),
                ('postal_code', models.CharField(db_column='cep', max_length=45, verbose_name='CEP')),
                ('tax_id', models.CharField(db_column='cnpj', max_length=45, verbose_name='CNPJ')),
                ('state', models.ForeignKey(db_column='id_estado', on_delete=django.db.models.deletion.DO_NOTHING, to='locations.state', verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Instância',
                'verbose_name_plural': 'Instâncias',
                'db_table': 'instancias',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.AutoField(db_column='id_cidade', primary_key=True, serialize=False, verbose_name='ID da Cidade')),
                ('name', models.CharField(db_column='nome', max_length=45, verbose_name='Nome')),
                ('state_id', models.ForeignKey(db_column='id_estado', on_delete=django.db.models.deletion.DO_NOTHING, to='locations.state', verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Cidade',
                'verbose_name_plural': 'Cidades',
                'db_table': 'cidades',
            },
        ),
    ]
