# Generated by Django 5.1.2 on 2024-10-17 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Housing',
            fields=[
                ('housing_id', models.AutoField(db_column='id_moradia', primary_key=True, serialize=False)),
                ('description', models.CharField(db_column='descricao', max_length=255)),
            ],
            options={
                'verbose_name': 'Moradia',
                'verbose_name_plural': 'Moradias',
                'db_table': 'moradia',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('state_id', models.AutoField(db_column='id_estado', primary_key=True, serialize=False)),
                ('uf', models.CharField(db_column='uf', max_length=2)),
                ('name', models.CharField(db_column='nome', max_length=45)),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
                'db_table': 'estados',
            },
        ),
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('instance_id', models.AutoField(db_column='id_instancia', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='nome', max_length=45)),
                ('address', models.CharField(db_column='endereco', max_length=45)),
                ('neighborhood', models.CharField(db_column='bairro', max_length=45)),
                ('postal_code', models.CharField(db_column='cep', max_length=45)),
                ('tax_id', models.CharField(db_column='cnpj', max_length=45)),
                ('state_id', models.ForeignKey(db_column='id_estado', on_delete=django.db.models.deletion.DO_NOTHING, to='locations.state')),
            ],
            options={
                'verbose_name': 'Instância',
                'verbose_name_plural': 'Instâncias',
                'db_table': 'instancias',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.AutoField(db_column='id_cidade', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='nome', max_length=45)),
                ('state_id', models.ForeignKey(db_column='id_estado', on_delete=django.db.models.deletion.DO_NOTHING, to='locations.state')),
            ],
            options={
                'verbose_name': 'Cidade',
                'verbose_name_plural': 'Cidades',
                'db_table': 'cidades',
            },
        ),
    ]
