# Generated by Django 5.1.2 on 2024-11-05 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='city_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='city',
            old_name='state_id',
            new_name='state',
        ),
    ]
