# Generated by Django 5.1.2 on 2024-11-06 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_rename_city_id_city_id_rename_state_id_city_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='id',
            field=models.BigAutoField(db_column='id_instancia', primary_key=True, serialize=False, verbose_name='ID da Instância'),
        ),
    ]
