# Generated by Django 5.1.2 on 2024-11-07 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_alter_instance_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='tax_id',
            field=models.CharField(db_column='cnpj', max_length=45, unique=True, verbose_name='CNPJ'),
        ),
    ]
