# Generated by Django 5.1.2 on 2024-10-30 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('administration', '0001_initial'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Week',
            fields=[
                ('day_id', models.AutoField(db_column='id_dia', primary_key=True, serialize=False, verbose_name='ID do Dia')),
                ('description', models.CharField(db_column='descricao', max_length=45, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Dia da Semana',
                'verbose_name_plural': 'Dias da Semana',
                'db_table': 'semana',
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('shift_id', models.AutoField(db_column='id_turno', primary_key=True, serialize=False, verbose_name='ID do Turno')),
                ('description', models.CharField(db_column='descricao', max_length=45, verbose_name='Descrição')),
                ('instance_id', models.ForeignKey(db_column='id_instancia', on_delete=django.db.models.deletion.DO_NOTHING, to='locations.instance', verbose_name='Instância')),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
                'db_table': 'turnos',
            },
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('class_id', models.AutoField(db_column='id_turma', primary_key=True, serialize=False, verbose_name='ID da Turma')),
                ('description', models.CharField(db_column='descricao', max_length=45, verbose_name='Descrição')),
                ('start_time', models.CharField(db_column='horario_inicio', max_length=45, verbose_name='Horário de Início')),
                ('end_time', models.CharField(db_column='horario_fim', max_length=45, verbose_name='Horário de Fim')),
                ('eja', models.IntegerField(db_column='eja', verbose_name='EJA')),
                ('room_id', models.ForeignKey(db_column='id_sala', on_delete=django.db.models.deletion.DO_NOTHING, to='administration.room', verbose_name='Sala')),
                ('school_year_id', models.ForeignKey(db_column='id_ano_escolar', on_delete=django.db.models.deletion.DO_NOTHING, to='academics.schoolyear', verbose_name='Ano Escolar')),
                ('shift_id', models.ForeignKey(db_column='id_turno', on_delete=django.db.models.deletion.DO_NOTHING, to='management.shift', verbose_name='Turno')),
            ],
            options={
                'verbose_name': 'Turma',
                'verbose_name_plural': 'Turmas',
                'db_table': 'turmas',
            },
        ),
    ]
