# Generated by Django 5.1.2 on 2024-11-05 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSchedule',
            fields=[
                ('class_schedule_id', models.AutoField(db_column='id_horario_aula', primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=45)),
                ('schedule_time', models.CharField(max_length=45)),
                ('last_updated', models.DateField(db_column='data_atualizacao')),
            ],
            options={
                'verbose_name': 'Horário de aula',
                'verbose_name_plural': 'Horários de aulas',
                'db_table': 'horarios_aulas',
            },
        ),
        migrations.CreateModel(
            name='ContractType',
            fields=[
                ('contract_type_id', models.AutoField(db_column='id_tipo', primary_key=True, serialize=False, verbose_name='ID do Tipo')),
                ('description', models.CharField(db_column='descricao', max_length=45, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Tipo de contrato',
                'verbose_name_plural': 'Tipos de contrato',
                'db_table': 'tipo_contrato',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(db_column='id_funcionario', primary_key=True, serialize=False, verbose_name='ID do Funcionário')),
                ('name', models.CharField(db_column='nome', max_length=255, verbose_name='Nome')),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], db_column='sexo', max_length=1, verbose_name='Sexo')),
                ('birth_date', models.DateField(db_column='data_nascimento', verbose_name='Data de Nascimento')),
                ('rg', models.CharField(blank=True, db_column='rg', max_length=45, null=True, verbose_name='RG')),
                ('cpf', models.CharField(db_column='cpf', max_length=11, unique=True, verbose_name='CPF')),
                ('photo', models.TextField(blank=True, db_column='foto', null=True, verbose_name='Foto')),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
                'db_table': 'funcionarios',
            },
        ),
        migrations.CreateModel(
            name='EmployeeSchool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('super_user', 'Super Usuário'), ('admin', 'Admin'), ('gestor', 'Gestor'), ('docente', 'Docente')], db_column='tipo', max_length=11, verbose_name='Tipo de Usuário')),
            ],
            options={
                'verbose_name': 'Funcionário alocado na escola',
                'verbose_name_plural': 'Funcionários alocados nas escolas',
                'db_table': 'funcionarios_escolas',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('position_id', models.AutoField(db_column='id_cargo', primary_key=True, serialize=False, verbose_name='ID do Cargo')),
                ('description', models.CharField(db_column='descricao', max_length=45, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
                'db_table': 'cargos',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('classroom_id', models.AutoField(db_column='id_sala', primary_key=True, serialize=False, verbose_name='ID da Sala')),
                ('description', models.CharField(db_column='descricao', max_length=45, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Sala',
                'verbose_name_plural': 'Salas',
                'db_table': 'salas',
            },
        ),
        migrations.CreateModel(
            name='ScheduleGrid',
            fields=[
                ('schedule_grid_id', models.AutoField(db_column='id_grade_horario', primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Grade de horário',
                'verbose_name_plural': 'Grades de horários',
                'db_table': 'grades_horarios',
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(db_column='id_escola', primary_key=True, serialize=False, verbose_name='ID da Escola')),
                ('corporate_name', models.CharField(db_column='nome_razao', max_length=45, verbose_name='Nome ou Razão Social')),
                ('trade_name', models.CharField(db_column='nome_fantasia', max_length=45, verbose_name='Nome Fantasia')),
                ('address', models.CharField(db_column='endereco', max_length=45, verbose_name='Endereço')),
                ('neighborhood', models.CharField(db_column='bairro', max_length=45, verbose_name='Bairro')),
                ('email', models.CharField(max_length=45, verbose_name='Email')),
                ('postal_code', models.CharField(db_column='cep', max_length=45, verbose_name='CEP')),
                ('tax_id', models.CharField(db_column='cnpj', max_length=45, verbose_name='CNPJ')),
                ('inep_code', models.CharField(db_column='inep', max_length=45, verbose_name='Código INEP')),
                ('logo', models.TextField(verbose_name='Logotipo')),
                ('additional_field', models.CharField(blank=True, db_column='escolascol', max_length=45, null=True, verbose_name='Campo Adicional')),
            ],
            options={
                'verbose_name': 'Escola',
                'verbose_name_plural': 'Escolas',
                'db_table': 'escolas',
            },
        ),
        migrations.CreateModel(
            name='Schooling',
            fields=[
                ('schooling_id', models.AutoField(db_column='id_escolaridade', primary_key=True, serialize=False, verbose_name='ID da Escolaridade')),
                ('description', models.CharField(db_column='descricao', max_length=45, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Escolaridade',
                'verbose_name_plural': 'Escolaridades',
                'db_table': 'escolaridade',
            },
        ),
    ]
