# Generated by Django 5.1.2 on 2024-10-17 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('administration', '0001_initial'),
        ('locations', '0001_initial'),
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classschedule',
            name='shift',
            field=models.ForeignKey(db_column='id_turno', on_delete=django.db.models.deletion.DO_NOTHING, to='management.shift'),
        ),
        migrations.AddField(
            model_name='employeeschool',
            name='academic_year_id',
            field=models.ForeignKey(db_column='id_ano_letivo', on_delete=django.db.models.deletion.DO_NOTHING, to='academics.academicyear'),
        ),
        migrations.AddField(
            model_name='employeeschool',
            name='contract_type_id',
            field=models.ForeignKey(db_column='id_contrato', on_delete=django.db.models.deletion.DO_NOTHING, to='administration.contracttype'),
        ),
        migrations.AddField(
            model_name='employeeschool',
            name='employee_id',
            field=models.ForeignKey(db_column='id_funcionario', on_delete=django.db.models.deletion.DO_NOTHING, to='administration.employee'),
        ),
        migrations.AddField(
            model_name='employeeschool',
            name='position_id',
            field=models.ForeignKey(db_column='id_cargo', on_delete=django.db.models.deletion.DO_NOTHING, to='administration.position'),
        ),
        migrations.AddField(
            model_name='schedulegrid',
            name='class_time',
            field=models.ForeignKey(db_column='id_horario_aula', on_delete=django.db.models.deletion.DO_NOTHING, to='administration.classschedule'),
        ),
        migrations.AddField(
            model_name='schedulegrid',
            name='day',
            field=models.ForeignKey(db_column='id_dia', on_delete=django.db.models.deletion.DO_NOTHING, to='management.week'),
        ),
        migrations.AddField(
            model_name='schedulegrid',
            name='diary',
            field=models.ForeignKey(db_column='id_diario', on_delete=django.db.models.deletion.DO_NOTHING, to='academics.diary'),
        ),
        migrations.AddField(
            model_name='school',
            name='instance_id',
            field=models.ForeignKey(db_column='id_instancia', on_delete=django.db.models.deletion.DO_NOTHING, to='locations.instance'),
        ),
        migrations.AddField(
            model_name='room',
            name='school',
            field=models.ForeignKey(db_column='id_escola', on_delete=django.db.models.deletion.DO_NOTHING, to='administration.school'),
        ),
        migrations.AddField(
            model_name='employeeschool',
            name='school_id',
            field=models.ForeignKey(db_column='id_escola', on_delete=django.db.models.deletion.DO_NOTHING, to='administration.school'),
        ),
        migrations.AddField(
            model_name='employee',
            name='schooling_id',
            field=models.ForeignKey(db_column='id_escolaridade', on_delete=django.db.models.deletion.DO_NOTHING, to='administration.schooling'),
        ),
        migrations.AlterUniqueTogether(
            name='employeeschool',
            unique_together={('employee_id', 'school_id')},
        ),
    ]
