# Generated by Django 5.1.2 on 2024-11-07 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='inep_code',
            field=models.CharField(db_column='inep', max_length=45, unique=True, verbose_name='Código INEP'),
        ),
        migrations.AlterField(
            model_name='school',
            name='tax_id',
            field=models.CharField(db_column='cnpj', max_length=45, unique=True, verbose_name='CNPJ'),
        ),
    ]
