# Generated by Django 5.1.2 on 2024-10-18 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='schooling_id',
            new_name='schooling',
        ),
    ]
