# Generated by Django 5.1.2 on 2024-10-17 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frequency',
            fields=[
                ('frequency_id', models.AutoField(db_column='id_frequencia', primary_key=True, serialize=False)),
                ('presence', models.CharField(max_length=1)),
                ('lesson_content_id', models.ForeignKey(db_column='id_conteudo_aula', on_delete=django.db.models.deletion.DO_NOTHING, to='academics.lessoncontent')),
                ('student_enrollment', models.ForeignKey(db_column='aluno_matricula', on_delete=django.db.models.deletion.DO_NOTHING, to='students.student')),
            ],
            options={
                'verbose_name': 'Frequência',
                'verbose_name_plural': 'Frequências',
                'db_table': 'frequencias',
            },
        ),
        migrations.CreateModel(
            name='JustifiedAbsence',
            fields=[
                ('justified_absence_id', models.AutoField(db_column='id_falta_justificada', primary_key=True, serialize=False)),
                ('start_date', models.DateField(db_column='data_inicio')),
                ('end_date', models.DateField(blank=True, db_column='data_fim', null=True)),
                ('justification', models.TextField(db_column='justificativa')),
                ('file', models.TextField(blank=True, null=True)),
                ('student_class_id', models.ForeignKey(db_column='id_turma_aluno', on_delete=django.db.models.deletion.DO_NOTHING, to='students.studentclasses')),
            ],
            options={
                'verbose_name': 'Falta Justificada',
                'verbose_name_plural': 'Faltas Justificadas',
                'db_table': 'faltas_justificadas',
            },
        ),
        migrations.CreateModel(
            name='SysPresence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_column='data')),
                ('status', models.IntegerField(db_column='situacao')),
                ('student_class_id', models.ForeignKey(db_column='id_turma_aluno', on_delete=django.db.models.deletion.DO_NOTHING, to='students.studentclasses')),
            ],
            options={
                'verbose_name': 'Presença',
                'verbose_name_plural': 'Presenças',
                'db_table': 'sys_presenca',
            },
        ),
    ]
