from .school_year import SchoolYear
from .academic_year import AcademicYear
from .evaluation import Evaluation
from .curricular_component import CurricularComponent
from .lesson_content import LessonContent
from .diary import Diary
from .grade import Grade
from .curricular_component_matrix import CurricularComponentMatrix
from .curricular_matrix import CurricularMatrix
